Feat/favicon
StudioCompanion/companion-studio pull request #181
Opened 2022-05-17 14:57 UTC by elenamarinaki

### Why

Partially resolves #168 

### What

- copied the favicon package into the `public` folder of the application
- linked the metadata in the `_document.tsx` file

### Checklist

- [ ] Ready to be merged

2022-05-17 15:13 UTC, joshuaellis requested changes

2022-05-17 15:13 UTC, joshuaellis commented on packages/web/public/favicon/site.webmanifest
> +    "name": "",
This some of this content needs adding, I'd ask @willcompanion or @mylespalmer for the theme color

2022-05-17 15:13 UTC, joshuaellis commented on packages/web/src/pages/_document.tsx
> +            href={'android-chrome-256x256.png'}
this has an incorrect path?

2022-05-17 21:17 UTC, joshuaellis requested changes

2022-05-17 21:17 UTC, joshuaellis commented on packages/web/src/client/components/Site/SiteLayout.tsx
> +  setInterval(() => {
Here's an article that will help you understand how to use 'setInterval' in react - https://sebhastian.com/setinterval-react/

2022-05-17 21:17 UTC, joshuaellis commented on packages/web/src/client/components/Site/SiteLayout.tsx
> +          '<link rel="icon" href="' +
Im not the biggest fan of this method, it feels expensive to be destroying and creating nodes on the fly. Can we not just change the source of the link?

We could attach and ID to it, for example.

2022-05-18 09:38 UTC, elenamarinaki commented
@joshuaellis 
in this last PR, I am bringing back the `useEffect` to run the timer, since this has to be done client-side.

I am getting the `id` of the `setInterval` callback, so that I can clear it at the end. Inside, I am running the actual code:
1. I am checking if there is a `document` (it should be, we're on the client)
2. selecting the `<link />` element
3. I am mutating its `href` with the `setAttribute` method
4. lastly, I am updating the counter correctly, with a callback on its previous state

---

This is still not running, so I am still investigating as to why 🤔

2022-05-18 11:56 UTC, joshuaellis requested changes

2022-05-18 11:56 UTC, joshuaellis commented on packages/web/src/client/components/Site/SiteLayout.tsx
> +        if (counter === 150) {
```suggestion
        if (counter === 149) {
```

2022-05-18 13:48 UTC, joshuaellis approved these changes

2022-05-18 13:48 UTC, merged